-- ══════════════════════════════════════════════════════════
-- FITPRO — Seed exercices
-- À exécuter APRÈS schema.sql
-- ══════════════════════════════════════════════════════════

INSERT INTO exercises (
  name_fr, name_en,
  description_fr, description_en,
  instructions_fr, instructions_en,
  muscle_groups, secondary_muscles,
  goals, locations, difficulty, equipment,
  gif_url, contraindications,
  sets_recommended, reps_recommended, rest_seconds,
  calories_per_minute, is_premium
) VALUES

-- ══════════ PECTORAUX ══════════

('Pompes', 'Push-Up',
 'Exercice fondamental pour les pectoraux, triceps et épaules.',
 'Fundamental exercise for chest, triceps and shoulders.',
 ARRAY['Position planche, mains à largeur d''épaules','Descends jusqu''à 90° coudes','Pousse explosif vers le haut','Corps aligné du début à la fin'],
 ARRAY['Plank position, hands shoulder-width','Lower until elbows at 90°','Explode back up','Keep body aligned throughout'],
 ARRAY['chest','triceps','shoulders'], ARRAY['abs','lower_back'],
 ARRAY['renforcement','perte_gras','prise_muscle'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/push_up.gif',
 ARRAY['wrist_left','wrist_right','shoulder_left','shoulder_right'],
 3, '10-15', 60, 7.0, FALSE),

('Pompes diamant', 'Diamond Push-Up',
 'Pompes mains rapprochées en losange — cible l''intérieur des pectoraux et triceps.',
 'Close-grip push-up targeting inner chest and triceps.',
 ARRAY['Mains en losange sous la poitrine','Corps aligné','Descends lentement','Remonte en contractant triceps'],
 ARRAY['Form diamond with hands under chest','Body aligned','Lower slowly','Press up squeezing triceps'],
 ARRAY['chest','triceps'], ARRAY['shoulders'],
 ARRAY['renforcement','prise_muscle'], ARRAY['gym','home'],
 'intermediate', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/diamond_push_up.gif',
 ARRAY['wrist_left','wrist_right','elbow_left','elbow_right'],
 3, '8-12', 60, 7.5, FALSE),

('Développé couché haltères', 'Dumbbell Bench Press',
 'Développé couché aux haltères pour un meilleur étirement pectoral.',
 'Dumbbell press for greater chest stretch and range of motion.',
 ARRAY['Allonge-toi sur banc, haltères en haut','Descends jusqu''à la poitrine','Pousse vers le haut','Serre les pecs en haut'],
 ARRAY['Lie on bench, dumbbells up','Lower to chest level','Press upward','Squeeze chest at top'],
 ARRAY['chest','triceps'], ARRAY['shoulders'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym'],
 'intermediate', ARRAY['dumbbells','bench'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/db_bench_press.gif',
 ARRAY['shoulder_left','shoulder_right'],
 4, '8-12', 75, 8.0, FALSE),

('Développé couché barre', 'Barbell Bench Press',
 'Le roi des exercices pectoraux pour gagner en masse et force.',
 'The king of chest exercises for mass and strength.',
 ARRAY['Allonge-toi sur le banc','Saisit la barre légèrement plus large que les épaules','Descends la barre jusqu''à la poitrine','Pousse explosif en expirant'],
 ARRAY['Lie on bench','Grip bar slightly wider than shoulders','Lower to chest','Explosive press while exhaling'],
 ARRAY['chest','triceps','shoulders'], ARRAY[]::TEXT[],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym'],
 'intermediate', ARRAY['barbell','bench'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/bench_press.gif',
 ARRAY['shoulder_left','shoulder_right','wrist_left','wrist_right'],
 4, '6-10', 90, 8.5, FALSE),

('Écarté haltères couché', 'Dumbbell Fly',
 'Isolation pectorale pour maximiser l''étirement et la contraction.',
 'Chest isolation for maximum stretch and contraction.',
 ARRAY['Allonge-toi sur banc, haltères au-dessus','Ouvre les bras en arc jusqu''à l''étirement','Referme en contractant fort'],
 ARRAY['Lie on bench, dumbbells above chest','Open arms in arc until stretch','Close squeezing chest hard'],
 ARRAY['chest'], ARRAY['shoulders'],
 ARRAY['prise_muscle'], ARRAY['gym'],
 'intermediate', ARRAY['dumbbells','bench'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/dumbbell_flyes.gif',
 ARRAY['shoulder_left','shoulder_right'],
 3, '12-15', 60, 6.5, TRUE),

-- ══════════ DOS ══════════

('Traction pronation', 'Pull-Up',
 'Exercice complet pour le dos et les biceps. Le meilleur poids du corps.',
 'Best bodyweight exercise for back and biceps.',
 ARRAY['Barre en prise pronation, bras tendus','Tire jusqu''au menton au-dessus de la barre','Descends lentement et contrôle'],
 ARRAY['Overhand grip, arms extended','Pull until chin over bar','Lower slowly with control'],
 ARRAY['back','biceps','lats'], ARRAY['shoulders','abs'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym','home'],
 'intermediate', ARRAY['pull_up_bar'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/pull_up.gif',
 ARRAY['shoulder_left','shoulder_right','elbow_left','elbow_right'],
 4, '5-10', 90, 9.0, FALSE),

('Traction supination', 'Chin-Up',
 'Traction en supination — cible davantage les biceps.',
 'Underhand grip pull-up — more bicep involvement.',
 ARRAY['Barre en prise supination (paumes vers toi)','Tire jusqu''au menton','Descends lentement'],
 ARRAY['Underhand grip (palms facing you)','Pull until chin clears bar','Lower slowly'],
 ARRAY['back','biceps'], ARRAY['lats'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym','home'],
 'intermediate', ARRAY['pull_up_bar'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/chin_up.gif',
 ARRAY['elbow_left','elbow_right','shoulder_left','shoulder_right'],
 4, '6-10', 90, 8.5, FALSE),

('Rowing haltère unilatéral', 'Single-Arm Dumbbell Row',
 'Rowing unilatéral pour corriger les déséquilibres et épaissir le dos.',
 'Unilateral rowing to fix imbalances and build back thickness.',
 ARRAY['Genou et main sur banc','Haltère dans l''autre main, dos plat','Tire le coude vers le plafond','Serre le dos en haut'],
 ARRAY['Knee and hand on bench','Dumbbell in other hand, flat back','Drive elbow toward ceiling','Squeeze back at top'],
 ARRAY['back','biceps','lats'], ARRAY['traps'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym'],
 'beginner', ARRAY['dumbbells','bench'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/db_row.gif',
 ARRAY['back_lower'],
 4, '10-12', 60, 7.0, FALSE),

('Rowing barre', 'Barbell Row',
 'Développe l''épaisseur globale du dos.',
 'Builds overall back thickness.',
 ARRAY['Penche-toi à 45°, dos plat','Saisit la barre en pronation','Tire vers le nombril','Serre les omoplates'],
 ARRAY['Hinge to 45°, flat back','Overhand grip on bar','Pull to navel','Squeeze shoulder blades'],
 ARRAY['back','lats','biceps'], ARRAY['lower_back','traps'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym'],
 'intermediate', ARRAY['barbell'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/barbell_row.gif',
 ARRAY['back_lower','back_upper'],
 4, '8-12', 90, 8.0, FALSE),

('Soulevé de terre', 'Deadlift',
 'L''exercice le plus complet — mobilise 70% des muscles du corps.',
 'The most complete exercise — recruits 70% of body muscles.',
 ARRAY['Pieds à largeur de hanche, barre sur les pieds','Saisit la barre, dos plat et poitrine haute','Pousse le sol et soulève','Debout, hanches et genoux en même temps'],
 ARRAY['Feet hip-width, bar over feet','Grip bar, flat back chest up','Push floor away to lift','Hips and knees extend together'],
 ARRAY['back','glutes','hamstrings','lower_back'], ARRAY['quads','traps','forearms'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym'],
 'intermediate', ARRAY['barbell'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/deadlift.gif',
 ARRAY['back_lower','back_upper','knee_left','knee_right'],
 4, '5-6', 120, 10.0, TRUE),

-- ══════════ JAMBES ══════════

('Squat poids du corps', 'Bodyweight Squat',
 'La base de tout entraînement jambes, sans équipement.',
 'The foundation of all leg training, no equipment needed.',
 ARRAY['Pieds à largeur d''épaules, pointes vers l''extérieur','Descends comme pour t''asseoir','Cuisses parallèles au sol','Remonte en poussant sur les talons'],
 ARRAY['Feet shoulder-width, toes slightly out','Sit back and down','Thighs parallel to floor','Drive up through heels'],
 ARRAY['quads','glutes','hamstrings'], ARRAY['calves','lower_back','abs'],
 ARRAY['renforcement','perte_gras','prise_muscle'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/squat.gif',
 ARRAY['knee_left','knee_right','hip','back_lower'],
 4, '15-20', 60, 8.0, FALSE),

('Squat barre', 'Barbell Back Squat',
 'Le roi des exercices pour développer la masse des jambes.',
 'The king of leg exercises for building mass.',
 ARRAY['Barre sur les trapèzes, pieds à largeur d''épaules','Descends lentement en gardant le dos droit','Cuisses parallèles ou en dessous','Remonte en poussant sur tout le pied'],
 ARRAY['Bar on traps, feet shoulder-width','Descend slowly keeping back straight','Thighs parallel or below','Drive up through full foot'],
 ARRAY['quads','glutes','hamstrings'], ARRAY['lower_back','abs','calves'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym'],
 'intermediate', ARRAY['barbell','squat_rack'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/barbell_squat.gif',
 ARRAY['knee_left','knee_right','back_lower','hip'],
 5, '6-10', 120, 9.0, TRUE),

('Fentes avant', 'Forward Lunge',
 'Excellent pour l''équilibre et le travail unilatéral des jambes.',
 'Great for balance and unilateral leg development.',
 ARRAY['Grand pas en avant','Descends le genou arrière vers le sol','Genou avant dans l''axe du pied','Remonte et alterne les jambes'],
 ARRAY['Take big step forward','Lower back knee toward floor','Front knee over ankle','Return and alternate legs'],
 ARRAY['quads','glutes','hamstrings'], ARRAY['calves','abs'],
 ARRAY['renforcement','perte_gras'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/lunge.gif',
 ARRAY['knee_left','knee_right','hip'],
 3, '12 chaque', 60, 7.5, FALSE),

('Fentes latérales', 'Lateral Lunge',
 'Fentes sur le côté pour travailler les adducteurs et les fessiers.',
 'Side lunges targeting adductors and glutes.',
 ARRAY['Grand pas sur le côté','Fléchis le genou de la jambe d''appui','Garde l''autre jambe tendue','Pousse pour revenir'],
 ARRAY['Take big step to the side','Bend supporting leg knee','Keep other leg straight','Push to return'],
 ARRAY['quads','glutes'], ARRAY['hamstrings','calves'],
 ARRAY['renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/lateral_lunge.gif',
 ARRAY['knee_left','knee_right','hip'],
 3, '10 chaque', 60, 7.0, FALSE),

('Pont fessier', 'Glute Bridge',
 'Isole parfaitement les fessiers sans stress sur le bas du dos.',
 'Perfectly isolates glutes with minimal lower back stress.',
 ARRAY['Allonge-toi sur le dos, genoux pliés','Pousse les hanches vers le haut','Contracte les fessiers 2 secondes en haut','Descends lentement'],
 ARRAY['Lie on back, knees bent','Drive hips upward','Squeeze glutes 2 seconds at top','Lower slowly'],
 ARRAY['glutes','hamstrings'], ARRAY['abs','lower_back'],
 ARRAY['renforcement','prise_muscle'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/glute_bridge.gif',
 ARRAY['back_lower'],
 3, '15-20', 45, 5.5, FALSE),

('Hip thrust barre', 'Barbell Hip Thrust',
 'L''exercice roi pour développer la masse des fessiers.',
 'The king exercise for glute mass development.',
 ARRAY['Dos appuyé sur banc, barre sur les hanches','Pousse les hanches vers le plafond','Contracte les fessiers en haut','Descends de façon contrôlée'],
 ARRAY['Upper back on bench, bar on hips','Drive hips toward ceiling','Squeeze glutes at top','Lower with control'],
 ARRAY['glutes'], ARRAY['hamstrings','lower_back'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym'],
 'intermediate', ARRAY['barbell','bench'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/hip_thrust.gif',
 ARRAY['back_lower','hip'],
 4, '10-12', 75, 6.0, TRUE),

('Extension jambes', 'Leg Extension',
 'Isolation quadriceps sur machine.',
 'Quad isolation on machine.',
 ARRAY['Assis sur la machine','Bloque les chevilles sous les patins','Étends les jambes sans verrouiller les genoux','Descends lentement'],
 ARRAY['Sit on machine','Lock ankles under pads','Extend legs without locking knees','Lower slowly'],
 ARRAY['quads'], ARRAY[]::TEXT[],
 ARRAY['renforcement','prise_muscle'], ARRAY['gym'],
 'beginner', ARRAY['leg_extension_machine'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/leg_extension.gif',
 ARRAY['knee_left','knee_right'],
 3, '12-15', 60, 6.0, FALSE),

('Curl mollets debout', 'Standing Calf Raise',
 'Renforcement des mollets, essentiel pour la stabilité cheville.',
 'Calf strengthening essential for ankle stability.',
 ARRAY['Debout sur la pointe des pieds','Monte le plus haut possible','Maintiens 1 seconde','Descends lentement'],
 ARRAY['Stand on balls of feet','Rise as high as possible','Hold 1 second','Lower slowly'],
 ARRAY['calves'], ARRAY[]::TEXT[],
 ARRAY['renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/calf_raise.gif',
 ARRAY['ankle_left','ankle_right'],
 3, '15-20', 45, 5.0, FALSE),

-- ══════════ ÉPAULES ══════════

('Élévation latérale', 'Lateral Raise',
 'Isolation du deltoïde moyen pour élargir les épaules.',
 'Middle delt isolation for shoulder width.',
 ARRAY['Debout, haltères le long du corps','Monte les bras à l''horizontal','Légère flexion des coudes','Descends lentement'],
 ARRAY['Standing, dumbbells at sides','Raise arms to horizontal','Slight elbow bend','Lower slowly'],
 ARRAY['shoulders'], ARRAY[]::TEXT[],
 ARRAY['renforcement','prise_muscle'], ARRAY['gym','home'],
 'beginner', ARRAY['dumbbells'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/lateral_raise.gif',
 ARRAY['shoulder_left','shoulder_right'],
 3, '12-15', 45, 5.0, FALSE),

('Développé militaire haltères', 'Dumbbell Shoulder Press',
 'Développe les deltoïdes antérieurs et la force des épaules.',
 'Builds front delts and shoulder strength.',
 ARRAY['Assis, haltères au niveau des oreilles','Pousse vers le haut','Bras presque tendus sans verrouiller','Descends contrôlé'],
 ARRAY['Seated, dumbbells at ear level','Press upward','Arms almost extended without locking','Lower with control'],
 ARRAY['shoulders','triceps'], ARRAY['traps'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY['dumbbells'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/db_shoulder_press.gif',
 ARRAY['shoulder_left','shoulder_right','neck'],
 4, '10-12', 75, 7.0, FALSE),

('Oiseau haltères', 'Dumbbell Rear Delt Fly',
 'Isole le deltoïde postérieur souvent négligé.',
 'Isolates the often-neglected rear delt.',
 ARRAY['Penché en avant à 45°','Haltères pendants','Monte les bras sur les côtés','Serre les omoplates en haut'],
 ARRAY['Hinged forward at 45°','Dumbbells hanging','Raise arms to sides','Squeeze shoulder blades at top'],
 ARRAY['shoulders'], ARRAY['traps','back'],
 ARRAY['renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY['dumbbells'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/rear_delt_fly.gif',
 ARRAY['shoulder_left','shoulder_right'],
 3, '12-15', 45, 5.0, FALSE),

-- ══════════ BICEPS ══════════

('Curl haltères alternés', 'Alternating Dumbbell Curl',
 'Curl biceps en alternant les bras pour une meilleure contraction.',
 'Alternating bicep curls for better mind-muscle connection.',
 ARRAY['Debout, haltères en supination','Plie un coude à la fois','Amène l''haltère vers l''épaule','Descends lentement, alterne'],
 ARRAY['Standing, dumbbells supinated','Curl one arm at a time','Bring to shoulder','Lower slowly, alternate'],
 ARRAY['biceps'], ARRAY['forearms'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY['dumbbells'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/alt_curl.gif',
 ARRAY['elbow_left','elbow_right','wrist_left','wrist_right'],
 3, '10-12', 60, 5.5, FALSE),

('Curl marteau', 'Hammer Curl',
 'Curl en prise neutre pour les brachioradialis et biceps.',
 'Neutral grip curl targeting brachioradialis and biceps.',
 ARRAY['Haltères en prise neutre (pouces vers le haut)','Plie les coudes sans tourner les poignets','Amène au niveau des épaules','Descends lentement'],
 ARRAY['Neutral grip (thumbs up)','Curl without rotating wrists','Bring to shoulder level','Lower slowly'],
 ARRAY['biceps','forearms'], ARRAY[]::TEXT[],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY['dumbbells'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/hammer_curl.gif',
 ARRAY['elbow_left','elbow_right','wrist_left','wrist_right'],
 3, '10-12', 60, 5.5, FALSE),

-- ══════════ TRICEPS ══════════

('Extension triceps poulie haute', 'Tricep Pushdown',
 'Isolation triceps sur câble pour une brûlure intense.',
 'Cable tricep isolation for intense muscle burn.',
 ARRAY['Debout face à la poulie haute','Tire la barre vers le bas','Bras tendus sans verrouiller','Remonte lentement'],
 ARRAY['Stand facing high pulley','Push bar downward','Arms extended without locking','Return slowly'],
 ARRAY['triceps'], ARRAY[]::TEXT[],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym'],
 'beginner', ARRAY['cable_machine'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/tricep_pushdown.gif',
 ARRAY['elbow_left','elbow_right'],
 3, '12-15', 60, 5.5, FALSE),

('Dips banc', 'Bench Dip',
 'Dips sur banc pour isoler les triceps sans matériel lourd.',
 'Bench dips to isolate triceps with minimal equipment.',
 ARRAY['Mains sur banc derrière toi','Jambes tendues devant','Descends en pliant les coudes à 90°','Remonte en poussant sur les mains'],
 ARRAY['Hands on bench behind you','Legs extended in front','Lower bending elbows to 90°','Press back up'],
 ARRAY['triceps'], ARRAY['chest','shoulders'],
 ARRAY['renforcement','prise_muscle'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/bench_dip.gif',
 ARRAY['shoulder_left','shoulder_right','wrist_left','wrist_right','elbow_left','elbow_right'],
 3, '12-15', 60, 6.0, FALSE),

-- ══════════ ABDOMINAUX ══════════

('Planche', 'Plank',
 'Gainage isométrique complet. Le fondement du core.',
 'Full isometric core exercise. The foundation of core training.',
 ARRAY['Position pompe sur les avant-bras','Corps aligné tête-talons','Contracte abdos et fessiers','Maintiens sans cambrer ni arrondir'],
 ARRAY['Forearm plank position','Body aligned head to heels','Squeeze abs and glutes','Hold without sagging or piking'],
 ARRAY['abs','obliques','lower_back'], ARRAY['shoulders','glutes'],
 ARRAY['renforcement','perte_gras','prise_muscle'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/plank.gif',
 ARRAY['wrist_left','wrist_right','back_lower'],
 3, '30-60 sec', 45, 5.0, FALSE),

('Planche latérale', 'Side Plank',
 'Gainage latéral pour les obliques et la stabilité du tronc.',
 'Lateral plank for obliques and trunk stability.',
 ARRAY['Sur l''avant-bras latéralement','Hanches soulevées en ligne droite','Maintiens la position','Change de côté'],
 ARRAY['On forearm laterally','Hips raised in straight line','Hold position','Switch sides'],
 ARRAY['obliques','abs'], ARRAY['shoulders'],
 ARRAY['renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/side_plank.gif',
 ARRAY['wrist_left','wrist_right','back_lower','shoulder_left','shoulder_right'],
 3, '20-40 sec', 45, 4.5, FALSE),

('Crunch', 'Crunch',
 'Flexion du tronc pour contracter les abdominaux supérieurs.',
 'Trunk flexion for upper abdominal contraction.',
 ARRAY['Allonge-toi, genoux pliés','Mains derrière la nuque','Soulève les épaules en contractant les abdos','Reviens sans poser la tête'],
 ARRAY['Lie down, knees bent','Hands behind neck','Lift shoulders contracting abs','Lower without resting head'],
 ARRAY['abs'], ARRAY['obliques'],
 ARRAY['renforcement','perte_gras'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/crunch.gif',
 ARRAY['neck','back_upper'],
 3, '15-25', 45, 5.0, FALSE),

('Mountain climber', 'Mountain Climber',
 'Cardio intense en gainage — abdos et fréquence cardiaque combinés.',
 'Intense cardio plank — abs and heart rate combined.',
 ARRAY['Position pompe, corps aligné','Ramène un genou vers la poitrine rapidement','Alterne à haute vitesse','Garde les hanches stables'],
 ARRAY['Push-up position, body aligned','Drive one knee to chest quickly','Alternate at high speed','Keep hips stable'],
 ARRAY['abs','cardio','full_body'], ARRAY['shoulders'],
 ARRAY['perte_gras','renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/mountain_climber.gif',
 ARRAY['wrist_left','wrist_right','back_lower'],
 4, '30 sec', 30, 11.0, FALSE),

('Russian twist', 'Russian Twist',
 'Rotation du tronc pour renforcer les obliques.',
 'Trunk rotation to strengthen obliques.',
 ARRAY['Assis, jambes légèrement soulevées','Tourne le tronc d''un côté à l''autre','Touche le sol de chaque côté','Garde le dos droit'],
 ARRAY['Seated, legs slightly raised','Rotate trunk side to side','Touch floor each side','Keep back straight'],
 ARRAY['obliques','abs'], ARRAY[]::TEXT[],
 ARRAY['renforcement','perte_gras'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/russian_twist.gif',
 ARRAY['back_lower','back_upper'],
 3, '20 reps', 45, 5.5, FALSE),

-- ══════════ CARDIO / PERTE DE GRAS ══════════

('Burpee', 'Burpee',
 'L''exercice HIIT complet — brûleur de calories maximum.',
 'The ultimate full-body HIIT exercise.',
 ARRAY['Debout → squattez, posez les mains','Sautez en position pompe','Pompe (optionnel)','Revenez et sautez en l''air bras tendus'],
 ARRAY['Stand → squat, place hands','Jump to plank','Push-up (optional)','Return and jump up arms overhead'],
 ARRAY['full_body','cardio'], ARRAY[]::TEXT[],
 ARRAY['perte_gras'], ARRAY['gym','home'],
 'intermediate', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/burpee.gif',
 ARRAY['back_lower','knee_left','knee_right','wrist_left','wrist_right'],
 4, '10', 45, 12.0, FALSE),

('Jumping jacks', 'Jumping Jacks',
 'Cardio doux pour activer tout le corps en douceur.',
 'Gentle cardio to activate the whole body.',
 ARRAY['Pieds joints, bras le long du corps','Saute en écartant pieds et bras','Reviens à la position initiale','Enchaîne à rythme régulier'],
 ARRAY['Feet together arms at sides','Jump feet out raising arms','Return to start','Maintain steady rhythm'],
 ARRAY['cardio','full_body'], ARRAY[]::TEXT[],
 ARRAY['perte_gras'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/jumping_jacks.gif',
 ARRAY['knee_left','knee_right','ankle_left','ankle_right'],
 3, '45 sec', 30, 9.0, FALSE),

('Genoux hauts', 'High Knees',
 'Course sur place intense avec genoux levés haut.',
 'Intense running in place with high knee drive.',
 ARRAY['Cours sur place','Monte les genoux à hauteur de hanche','Balancement naturel des bras','Rythme soutenu'],
 ARRAY['Run in place','Lift knees to hip height','Natural arm swing','Maintain steady pace'],
 ARRAY['cardio','quads','abs'], ARRAY[]::TEXT[],
 ARRAY['perte_gras'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/high_knees.gif',
 ARRAY['knee_left','knee_right','ankle_left','ankle_right','hip'],
 4, '30 sec', 30, 10.0, FALSE),

('Squat sauté', 'Jump Squat',
 'Squat explosif pour combiner force jambes et cardio.',
 'Explosive squat combining leg strength and cardio.',
 ARRAY['Descends en squat','Saute explosif vers le haut','Atterris en douceur sur la pointe','Enchaîne immédiatement'],
 ARRAY['Lower into squat','Explode upward','Land softly on balls of feet','Immediately repeat'],
 ARRAY['quads','glutes','cardio'], ARRAY[]::TEXT[],
 ARRAY['perte_gras','renforcement'], ARRAY['gym','home'],
 'intermediate', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/jump_squat.gif',
 ARRAY['knee_left','knee_right','ankle_left','ankle_right','hip'],
 4, '12', 45, 11.0, FALSE),

('Corde à sauter', 'Jump Rope',
 'Le meilleur exercice cardio rapport intensité/résultats.',
 'The best cardio exercise for intensity vs results ratio.',
 ARRAY['Corde derrière toi','Lance et saute au rythme','Atterris sur la pointe des pieds','Maintiens un rythme régulier'],
 ARRAY['Rope behind you','Swing and jump in rhythm','Land on balls of feet','Maintain steady rhythm'],
 ARRAY['cardio','calves','full_body'], ARRAY[]::TEXT[],
 ARRAY['perte_gras'], ARRAY['gym','home'],
 'beginner', ARRAY['jump_rope'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/jump_rope.gif',
 ARRAY['ankle_left','ankle_right','knee_left','knee_right'],
 5, '60 sec', 30, 13.0, FALSE),

('Box jump', 'Box Jump',
 'Saut sur box pour développer la puissance explosive des jambes.',
 'Box jump for explosive leg power development.',
 ARRAY['Debout face à la box','Flexion rapide puis saut explosif','Atterris les deux pieds sur la box','Redescends en contrôlant'],
 ARRAY['Stand facing box','Quick dip then explosive jump','Land both feet on box','Step or jump back down'],
 ARRAY['quads','glutes','cardio'], ARRAY['calves','hamstrings'],
 ARRAY['perte_gras','renforcement'], ARRAY['gym'],
 'intermediate', ARRAY['plyo_box'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/box_jump.gif',
 ARRAY['knee_left','knee_right','ankle_left','ankle_right'],
 4, '8', 60, 10.0, TRUE),

-- ══════════ ÉTIREMENTS / RÉCUPÉRATION ══════════

('Étirement quadriceps debout', 'Standing Quad Stretch',
 'Étirement essentiel après un entraînement jambes.',
 'Essential stretch after a leg workout.',
 ARRAY['Debout sur une jambe','Attrape la cheville derrière toi','Genou pointé vers le sol','Maintiens 20-30 secondes'],
 ARRAY['Stand on one leg','Grab ankle behind you','Knee pointing down','Hold 20-30 seconds'],
 ARRAY['quads'], ARRAY[]::TEXT[],
 ARRAY['renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/quad_stretch.gif',
 ARRAY[]::TEXT[],
 1, '30 sec chaque', 0, 2.0, FALSE),

('Étirement ischio-jambiers', 'Hamstring Stretch',
 'Étirement fondamental pour prévenir les blessures.',
 'Fundamental stretch to prevent injuries.',
 ARRAY['Assis par terre, jambe tendue','Penche-toi vers les orteils','Garde le dos droit','Maintiens 20-30 secondes'],
 ARRAY['Sit on floor, leg extended','Reach toward toes','Keep back straight','Hold 20-30 seconds'],
 ARRAY['hamstrings'], ARRAY['lower_back'],
 ARRAY['renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/hamstring_stretch.gif',
 ARRAY[]::TEXT[],
 1, '30 sec chaque', 0, 2.0, FALSE),

('Yoga - Chien tête en bas', 'Downward Dog',
 'Étirement complet du corps — parfait pour les jours de repos.',
 'Full body stretch — perfect for rest days.',
 ARRAY['À quatre pattes','Pousse les hanches vers le plafond','Forme un V inversé','Maintiens 30 secondes en respirant'],
 ARRAY['On all fours','Push hips toward ceiling','Form inverted V','Hold 30 seconds breathing deeply'],
 ARRAY['hamstrings','calves','back','shoulders'], ARRAY[]::TEXT[],
 ARRAY['renforcement'], ARRAY['gym','home'],
 'beginner', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/downward_dog.gif',
 ARRAY['wrist_left','wrist_right'],
 3, '30 sec', 15, 2.5, FALSE),

-- ══════════ EXERCICES AVANCÉS (PREMIUM) ══════════

('Squat pistol', 'Pistol Squat',
 'Squat sur une jambe — l''apogée du contrôle et de la force.',
 'Single-leg squat — the pinnacle of control and strength.',
 ARRAY['Debout sur une jambe, autre tendue','Descends lentement en équilibre','Cuisse parallèle au sol','Remonte en contrôlant'],
 ARRAY['Stand on one leg, other extended','Lower slowly maintaining balance','Thigh parallel to floor','Rise with control'],
 ARRAY['quads','glutes','hamstrings'], ARRAY['abs','calves'],
 ARRAY['renforcement','prise_muscle'], ARRAY['gym','home'],
 'advanced', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/pistol_squat.gif',
 ARRAY['knee_left','knee_right','hip','ankle_left','ankle_right'],
 3, '5-8 chaque', 90, 8.0, TRUE),

('Muscle-up', 'Muscle-Up',
 'Traction + dip enchaînés — le Saint-Graal de la calisthenics.',
 'Pull-up + dip combined — the Holy Grail of calisthenics.',
 ARRAY['Traction explosive au-dessus de la barre','Transition : coudes passent au-dessus','Pousse vers le haut (dip)','Descends lentement'],
 ARRAY['Explosive pull above bar','Transition: elbows over bar','Press up like a dip','Lower with control'],
 ARRAY['back','chest','triceps','biceps','shoulders'], ARRAY['abs'],
 ARRAY['renforcement','prise_muscle'], ARRAY['gym','home'],
 'advanced', ARRAY['pull_up_bar'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/muscle_up.gif',
 ARRAY['shoulder_left','shoulder_right','elbow_left','elbow_right','wrist_left','wrist_right'],
 3, '3-5', 120, 11.0, TRUE),

('Pompes claquées', 'Clap Push-Up',
 'Pompes pliométriques pour développer la puissance des pectoraux.',
 'Plyometric push-ups for chest power development.',
 ARRAY['Position pompe standard','Descends normalement','Pousse explosif pour décoller','Claque les mains et atterris doux'],
 ARRAY['Standard push-up position','Lower normally','Explosive push to take off','Clap hands and land softly'],
 ARRAY['chest','triceps','shoulders'], ARRAY['abs'],
 ARRAY['renforcement'], ARRAY['gym','home'],
 'advanced', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/clap_push_up.gif',
 ARRAY['wrist_left','wrist_right','shoulder_left','shoulder_right'],
 3, '8-10', 90, 9.0, TRUE),

('Développé couché prise serrée', 'Close-Grip Bench Press',
 'Développé couché en prise serrée pour cibler les triceps.',
 'Close-grip bench press to target triceps.',
 ARRAY['Barre en prise serrée (main dans la largeur des épaules)','Descends en gardant les coudes proches','Pousse vers le haut','Serre les triceps en haut'],
 ARRAY['Close grip (hands inside shoulders)','Lower keeping elbows close','Press upward','Squeeze triceps at top'],
 ARRAY['triceps','chest'], ARRAY['shoulders'],
 ARRAY['prise_muscle','renforcement'], ARRAY['gym'],
 'intermediate', ARRAY['barbell','bench'],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/close_grip_bench.gif',
 ARRAY['wrist_left','wrist_right','elbow_left','elbow_right'],
 4, '8-10', 75, 7.5, TRUE),

('Gainage dynamique', 'Dynamic Plank',
 'Planche avec transitions pour augmenter la difficulté.',
 'Plank with transitions to increase difficulty.',
 ARRAY['Commence en planche basse','Monte sur les mains (pompe haute)','Redescends sur les avant-bras','Alterne côtés'],
 ARRAY['Start in forearm plank','Move to high plank (push-up position)','Return to forearm plank','Alternate sides'],
 ARRAY['abs','obliques','shoulders'], ARRAY['chest','triceps'],
 ARRAY['renforcement','perte_gras'], ARRAY['gym','home'],
 'intermediate', ARRAY[]::TEXT[],
 'https://fitpro-cdn.s3.amazonaws.com/gifs/dynamic_plank.gif',
 ARRAY['wrist_left','wrist_right','back_lower','shoulder_left','shoulder_right'],
 3, '10 transitions', 60, 7.0, TRUE);

-- ══════════════════════════════════════════════════════════
-- Vérification du seed
-- ══════════════════════════════════════════════════════════

SELECT
  COUNT(*) AS total_exercises,
  COUNT(*) FILTER (WHERE is_premium = FALSE) AS free_exercises,
  COUNT(*) FILTER (WHERE is_premium = TRUE)  AS premium_exercises,
  COUNT(*) FILTER (WHERE 'renforcement' = ANY(goals)) AS renforcement,
  COUNT(*) FILTER (WHERE 'perte_gras' = ANY(goals))   AS perte_gras,
  COUNT(*) FILTER (WHERE 'prise_muscle' = ANY(goals)) AS prise_muscle,
  COUNT(*) FILTER (WHERE 'gym' = ANY(locations))  AS gym_only,
  COUNT(*) FILTER (WHERE 'home' = ANY(locations)) AS home_available
FROM exercises;
